# Generated by Django 4.2.4 on 2023-08-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlist_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField()),
                ('title', models.CharField()),
                ('img_url', models.CharField()),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='wishlist_app.wishlist')),
            ],
        ),
    ]
